version: "3"
services:
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=kafka
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - ALLOW_PLAINTEXT_LISTENER=yes
