version: "3.5"
services:
  nats:
    image: nats
    ports:
      - "8222:8222"
    command: "-js --server_name nats --cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
  nats-1:
    image: nats
    command: "-js --server_name nats_1 --cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    depends_on: ["nats"]
  nats-2:
    image: nats
    command: "-js --server_name nats_2 --cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    depends_on: ["nats"]
    depends_on: ["nats"]
